use crate::*;
use near_sdk::BorshStorageKey;

/// Storage keys for collections of sub-struct in main contract
#[derive(BorshDeserialize, BorshSerialize, BorshStorageKey, Clone)]
pub enum StorageKey {
    AnchorContractWasm,
    OctToken,
    WrappedAppchainToken,
    NearFungibleTokenSymbols,
    NearFungibleTokens,
    NearFungibleTokensMap,
    NextValidatorSet,
    ValidatorSetHistories,
    ValidatorSetHistoriesMap,
    UnwithdrawnValidatorRewards,
    UnwithdrawnDelegatorRewards,
    UnbondedStakes,
    AppchainSettings,
    AnchorSettings,
    ProtocolSettings,
    StakingHistories,
    StakingHistoriesMap,
    AnchorEventHistories,
    AnchorEventHistoriesMap,
    AppchainNotificationHistories,
    AppchainNotificationHistoriesMap,
    PermissionlessActionsStatus,
    BeefyLightClientState,
    ValidatorProfiles,
    ValidatorProfilesIdSet,
    ValidatorProfilesMap,
    ValidatorProfilesIdMap,
    RewardDistributionRecords,
    RewardDistributionEraNumberSet,
    RewardDistributionEraNumberToNoncesMap,
    RewardDistributionRecordSet,
    UserStakingHistories,
    UserStakingHistoriesIdSet,
    UserStakingHistoriesMap,
    AppchainMessages,
    AppchainMessageNonces,
    AppchainMessageMap,
    AppchainMessageProcessingResultMap,
    AppchainMessageProcessingResults,
    AppchainMessageProcessingResultsNonceSet,
    AppchainMessageProcessingResultsMap,
    AppchainChallenges,
    AppchainChallengesMap,
    WrappedAppchainNFTs,
    WrappedAppchainNFTsClassIds,
    WrappedAppchainNFTsNFTs,
    WrappedAppchainNFTContractWasm,
    NativeNearToken,
    NearVaultContractWasm,
    ValidatorIdsOfEra(u64),
    ValidatorToDelegatorsMapOfEra(u64),
    DelegatorToValidatorsMapOfEra(u64),
    ValidatorsOfEra(u64),
    DelegatorsOfEra(u64),
    UnprofitableValidatorIdsOfEra(u64),
    ValidatorRewardsOfEra(u64),
    DelegatorRewardsOfEra(u64),
    DelegatorIdsInMapOfVToDOfEra {
        era_number: u64,
        validator_id: AccountId,
    },
    ValidatorIdsInMapOfDToVOfEra {
        era_number: u64,
        delegator_id: AccountId,
    },
    WrappedAppchainNFTsLockedTokenIdSet(String),
    RemovingValidatorSetSteps,
    ValidatorPubkeysInAppchain,
}
